codecov:
  require_ci_to_pass: yes
  ci:
    - travis-ci  # with travis-ci.com execution is faster, can keep
    - circleci

ignore:
  - 'scripts/*'

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: yes
    patch: yes
    changes: no
