fail_fast: false
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/PyCQA/flake8
    rev: ''
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^docs/
